import { apiClient } from "../api-client"
import { API_ENDPOINTS } from "../constants"
import AsyncStorage from "@react-native-async-storage/async-storage"

export interface Ad {
  id: string
  type: 'event' | 'campaign'
  title: string
  description: string
  imageUrl?: string
  businessName?: string
  eventTitle?: string
  eventStartTime?: string
  eventCreatorId?: string
  budgetTotal?: number
  budgetSpent?: number
  status: 'pending' | 'approved' | 'rejected'
  autoGenerated: boolean
  createdAt: string
  ctaText?: string
  ctaUrl?: string
}

export interface EventAd extends Ad {
  type: 'event'
  eventTitle: string
  eventStartTime: string
  eventCreatorId: string
  location?: string
  attendeeCount?: number
  maxAttendees?: number
  isAttending?: boolean
}

export interface CampaignAd extends Ad {
  type: 'campaign'
  businessName: string
  campaignName: string
  website?: string
  phone?: string
}

export interface AdResponse {
  success: boolean
  data: Ad[]
  count: number
}

class AdService {
  async getAds(): Promise<Ad[]> {
    try {
      // Check if user has ad-free subscription
      const hasAdFreeSubscription = await this.checkAdFreeSubscription()
      if (hasAdFreeSubscription) {
        console.log('[AdService] User has ad-free subscription, returning empty ads')
        return []
      }

      const response = await apiClient.get<AdResponse | Ad[]>(API_ENDPOINTS.ADS.GET_ADS, {
        requiresAuth: true,
      })

      if (Array.isArray(response)) {
        return response
      }

      return response?.data || []
    } catch (error) {
      console.error('[AdService] Error fetching ads:', error)
      return []
    }
  }

  private async checkAdFreeSubscription(): Promise<boolean> {
    try {
      const subscriptionStr = await AsyncStorage.getItem('subscription')
      if (!subscriptionStr) return false
      
      const subscription = JSON.parse(subscriptionStr)
      return subscription?.hasAdFreeAccess || subscription?.plan === 'premium' || subscription?.plan === 'vip'
    } catch (error) {
      return false
    }
  }

  async trackImpression(adId: string): Promise<void> {
    try {
      await apiClient.post(API_ENDPOINTS.ADS.TRACK_IMPRESSION(adId))
    } catch (error) {
      console.error('[AdService] Error tracking impression:', error)
    }
  }

  async trackClick(adId: string): Promise<void> {
    try {
      await apiClient.post(API_ENDPOINTS.ADS.TRACK_CLICK(adId))
    } catch (error) {
      console.error('[AdService] Error tracking click:', error)
    }
  }

  async rsvpEventAd(adId: string, attending: boolean): Promise<{ success: boolean }> {
    try {
      return await apiClient.post(`/ads/event/${adId}/rsvp`, { attending })
    } catch (error) {
      console.error('[AdService] Error RSVPing to event ad:', error)
      return { success: false }
    }
  }

  isEventAd(ad: Ad): ad is EventAd {
    return ad.type === 'event'
  }

  isCampaignAd(ad: Ad): ad is CampaignAd {
    return ad.type === 'campaign'
  }
}

export const adService = new AdService()
